In [1]:
import numpy as np
mis_datos = np.arange(0,20)

In [2]:
print (mis_datos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
np.reshape(mis_datos, (5,4)) #Nota el default es opuesto al lenguaje de programación R

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
matr1 = np.reshape(mis_datos, (5,4), order="C") 
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
#Llegar hasta el número 9
matr1[2,1]

9

In [6]:
#Concepto Programación Orientada a Objetos POO
#np.reshape(mis_datos, (5,4))
type(mis_datos)

numpy.ndarray

In [22]:
matr1=np.array(mis_datos.reshape((5,4)))

In [24]:
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
matr1[2]

array([ 8,  9, 10, 11])

In [28]:
matr1[2,:]

array([ 8,  9, 10, 11])

In [30]:
matr1[:,2]

array([ 2,  6, 10, 14, 18])

In [18]:
mis_datos[2]

2

In [20]:
mis_datos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
 #Visualizaciones

In [9]:
import numpy as plt

In [10]:
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
 plt.plot(sueldo[0], c='Black', ls='--',marker='s', ms=7)

NameError: name 'sueldo' is not defined

In [16]:
def mi_func(lista1 = [1, 2, 3, 4, 5]):
    print(lista1)

mi_func(["Hola", "Python"])

['Hola', 'Python']
