In [1]:
# Ejercicio 1 - Crear lista - reshape - indexar

In [2]:
import numpy as np

In [3]:
lista = np.arange(10,40)

In [4]:
lista = lista.reshape (3,10)
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [5]:
lista [0,9]

19

In [6]:
# Ejercicio 2 - Crear array enteros aleatorios - reshape - indexar

In [7]:
import numpy as np
array = np.random.randint(0,100,9)
array

array([35, 49, 10, 66, 67,  5, 35,  2, 68])

In [8]:
matriz = array.reshape (3,3)
matriz

array([[35, 49, 10],
       [66, 67,  5],
       [35,  2, 68]])

In [9]:
matriz [2,2]

68

In [22]:
## Ejercicio 3 - diseñar funcion para generar N números aleatorios entre dos variables mínimo y máximo

import numpy as np

def generar_numeros_enteros_aleatorios(N, minimo, maximo):
    return np.random.randint (minimo, maximo, N)


# Ejemplo uso
N = 5
minimo = 1
maximo = 10
resultado = generar_numeros_enteros_aleatorios(N, minimo, maximo)
print (resultado)

[6 7 1 5 3]


In [26]:
import numpy as np

def generar_secuencia_numerica(minimo, maximo, paso):
    return np.arange(minimo, maximo, paso)

# Ejemplo uso

minimo = 0
maximo = 10
paso = 2

resultado = generar_secuencia_numerica(minimo, maximo, paso)
print (resultado)



[0 2 4 6 8]
