In [1]:
import numpy as np

In [3]:
array = np.random.randint(1,50,9)

In [5]:
array

array([ 9,  3, 13, 14,  5, 39,  5, 14, 13])

In [7]:
array = array.reshape(3,3)

In [9]:
array

array([[ 9,  3, 13],
       [14,  5, 39],
       [ 5, 14, 13]])

In [71]:
array [1:,2:]

array([[39],
       [13]])

In [104]:
array = np.arange(0,10)

In [106]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
array2 = np.arange (10,20)

In [110]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [112]:
array2 * array

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [114]:
np.sqrt(array2)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])